// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_JuanGuillen.DAL;

#nullable disable

namespace P1_AP1_JuanGuillen.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251011010654_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("DetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetallesId");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("TipoId");

                    b.ToTable("HuacalDetalles");
                });

            modelBuilder.Entity("P1_AP1_JuanGuillen.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Importe")
                        .HasColumnType("REAL");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("precio")
                        .HasColumnType("REAL");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradaHuacal");
                });

            modelBuilder.Entity("P1_AP1_JuanGuillen.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TipoHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Huacales verdes",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Huacales azules",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Huacales de huevos",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_AP1_JuanGuillen.Models.EntradasHuacales", "EntradaHuacal")
                        .WithMany("EntradasHuacalesDetalles")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_AP1_JuanGuillen.Models.TiposHuacales", "TipoHuacal")
                        .WithMany("EntradasHuacalesDetalle")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");

                    b.Navigation("TipoHuacal");
                });

            modelBuilder.Entity("P1_AP1_JuanGuillen.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalles");
                });

            modelBuilder.Entity("P1_AP1_JuanGuillen.Models.TiposHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
