// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_JuanGuillen.DAL;

#nullable disable

namespace P1_AP1_JuanGuillen.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250929223412_iniciar")]
    partial class iniciar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_JuanGuillen.Models.ControlHuacal", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("precio")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEntrada");

                    b.ToTable("Huacal");
                });
#pragma warning restore 612, 618
        }
    }
}
